Ext.namespace('Ext.ux');
Ext.ux.MyCombo=Ext.extend(Ext.form.ComboBox,{
	code:'',
	triggerAction:'all',
	valueField:'text',
	displayField:'text',
	onRender:function(ct,position){
		if(!this.store){
			var code=this.code;
			this.store=new Ext.data.SimpleStore({
				url:App.App_Info.BasePath+'/common/CommonAction.do?method=GetDictionarys&pcode='+pageCode+'&fcode='+code,
				fields:['value','text']
			})
		}
		Ext.ux.MyCombo.superclass.onRender.call(this, ct, position);
	}
});
Ext.reg('MyCombo',Ext.ux.MyCombo);
function LayoutEditorForm(){
	return {
		xtype:'form',
		frame:true,
		border:false,
		labelAlign:'right',
		labelWidth:80,
		autoScroll:true,
		defaults:{
			xtype:'fieldset',
			autoHeight:true,
			layout:'column',
			defaults:{
				bodyStyle:'padding-top:3px',
				layout:'form',
				defaults:{
					xtype:'textfield',
					anchor:'90%'
				}
			}
		},
		items:[
			{
				title:'基本信息',
				items:[
					{
						columnWidth:1,
						items:{
							fieldLabel:'课题名称',
							allowBlank:false,
							name:'name',
							anchor:'95%'
						}
					},{
						columnWidth:.5,
						items:[
							{
								fieldLabel:'课题编号',
								allowBlank:false,
								name:'serialNum'
							},{
								xtype:'MyCombo',
								fieldLabel:'课题密级',
								name:'secretLv',
								code:'secretLv'
							},{
								xtype:'MyCombo',
								fieldLabel:'所属单位',
								name:'belongUnit',
								code:'belongUnit'
							}
						]
					},{
						columnWidth:.5,
						items:[
							{
								fieldLabel:'负责人',
								name:'responser'
							},{
								xtype:'MyCombo',
								fieldLabel:'课题类型',
								name:'topicType',
								code:'topicType'
							},{
								fieldLabel:'所属科室',
								name:'belongWard'
							}
						]
					}
				]
			},{
				title:'详细信息',
				items:[
					{
						columnWidth:.5,
						items:[
							{
								xtype:'datefield',
								fieldLabel:'创建日期',
								name:'pj_createDate',
								readOnly:true,
								format:'Y-m-d',
								setValueEx:function(val){
									if(val&&val.time){
										this.el.dom.value=new Date(val.time).format('Y-m-d');
									}
								}
							},{
								xtype:'MyCombo',
								fieldLabel:'项目分类',
								name:'pj_class1',
								code:'pj_class1'
							},{
								xtype:'MyCombo',
								fieldLabel:'项目状态',
								name:'pj_status',
								code:'pj_status'
							},{
								fieldLabel:'企业投资',
								name:'pj_comInvest'
							},{
								fieldLabel:'地方费用',
								name:'pj_localCost'
							},{
								fieldLabel:'其它费用',
								name:'pj_otherCost'
							}
						]
					},{
						columnWidth:.5,
						items:[
							{
								xtype:'datefield',
								fieldLabel:'计划完成日期',
								name:'pj_completeDate',
								readOnly:true,
								format:'Y-m-d',
								setValueEx:function(val){
									if(val&&val.time){
										this.el.dom.value=new Date(val.time).format('Y-m-d');
									}
								}
							},{
								xtype:'MyCombo',
								fieldLabel:'项目子类',
								name:'pj_class2',
								code:'pj_class2'
							},{
								fieldLabel:'批准文号',
								name:'pj_icpNum'
							},{
								fieldLabel:'银行投资',
								name:'pj_bankInvest'
							},{
								fieldLabel:'中央财政费用',
								name:'pj_centerCost'
							},{
								fieldLabel:'项目总经费',
								name:'pj_totalCost'
							}
						]
					},{
						columnWidth:1,
						items:{
							xtype:'textarea',
							fieldLabel:'经费备注',
							name:'pj_desc',
							height:40,
							anchor:'95%'
						}
					}
				]
			},{
				title:'统计信息',
				items:[
					{
						columnWidth:.5,
						items:[
							{
								xtype:'MyCombo',
								fieldLabel:'学科分类',
								name:'tj_subjectClass',
								code:'tj_subjectClass'
							},{
								xtype:'MyCombo',
								fieldLabel:'国民经济大类',
								name:'tj_inteClass1',
								code:'tj_inteClass1'
							},{
								xtype:'MyCombo',
								fieldLabel:'项目来源',
								name:'tj_projectFrom',
								code:'tj_projectFrom'
							},{
								fieldLabel:'社会经济目标',
								name:'tj_societyTarget'
							}
						]
					},{
						columnWidth:.5,
						items:[
							{
								xtype:'MyCombo',
								fieldLabel:'研究类别',
								name:'tj_researchType',
								code:'tj_researchType'
							},{
								xtype:'MyCombo',
								fieldLabel:'国民经济小类',
								name:'tj_inteClass2',
								code:'tj_inteClass2'
							},{
								fieldLabel:'合作形式',
								name:'tj_cooperType'
							},{
								fieldLabel:'项目总人数',
								name:'tj_projectPersonNum'
							}
						]
					},{
						columnWidth:1,
						items:[
							{
								xtype:'textarea',
								fieldLabel:'备注',
								name:'tj_desc',
								height:40,
								anchor:'95%'
							},{
								xtype:'hidden',
								name:'id',
								value:'-1',
								listeners:{
									render:function(){
										var _form=this.ownerCt.ownerCt.ownerCt;
										if(_form.record){
											_form.form.loadRecord(_form.record);
											_form.form.findField('pj_createDate').setValueEx(_form.record.data['pj_createDate']);
											_form.form.findField('pj_completeDate').setValueEx(_form.record.data['pj_completeDate']);
										}
									}
								}
							}
						]
					}
				]
			}
		]
	};
}
function createEditorWin(_title,_record){
	new Ext.Window({
		title:_title,
		frame:true,
		closable:false,
		closeAction:'close',
		autoScroll:true,
		height:Ext.getBody().getSize().height*0.85,
		width:620,
		buttonAlign:'center',
		buttons:[
			{
				text:'保存',handler:function(){
					var _form=this.ownerCt.items.get(0).form;
					if(_form.isValid()){
						Ext.Ajax.request({
							url:App.App_Info.BasePath+'/admin/ResearchAdminAction.do',
							params:{method:'saveOrUpdate',data:Ext.util.JSON.encode(_form.getValues())},
							scope:this,
							success:function(_response,_options){
								if(Ext.util.JSON.decode(_response.responseText).success){
									alert('保存成功。');
									this.ownerCt.close();
									Ext.getCmp('grid').getStore().load({params:{start:0,limit:20}});
								}else{
									alert('保存失败，请检查填写后重新提交。');
								}
							}
						});
					}else{
						alert('请先完成表单再提交保存。');
					}
				}
			},{
				text:'关闭',handler:function(){
					this.ownerCt.close();
				}
			}
		],
		layout:'fit',
		items:Ext.apply(LayoutEditorForm(),{
			record:_record
		})
	}).show();
}
