var array={
	shiliang:[
		['无变化'],['增加'],['减少']
	],
	shuimian:[
		['无变化'],['好'],['差'],['多梦']
	],
	niaoliang:[
		['无变化'],['多尿'],['少尿']
	],
	tizhong:[
		['无变化'],['增加'],['减轻']
	],
	jingshen:[
		['无变化'],['好'],['差']
	],
	dabian:[
		['无变化']
	],
	yanbian:[
		['无变化']
	]
};
Ext.ns('Member.HR.RegistForm');
Member.HR.RegistForm=Ext.extend(Ext.Window,{
	initComponent:function(){
		var form=new Ext.form.FormPanel({
			bodyStyle:'padding-top:5px',
			labelWidth:60,
			labelAlign:'right',
			autoHeight:true,
			layout:'column',
			border:false,
			defaults:{
				columnWidth:.5,
				layout:'form',
				border:false,
				defaults:{
					anchor:'95%'
				}
			},
			items:[
				{
					columnWidth:1,
					items:[
						{
							xtype:'datefield',
							format:'Y-m-d',
							name:'registDate',
							fieldLabel:'登记日期',
							anchor:'47%',
							allowBlank:false
						},{
							xtype:'textfield',
							name:'symptom',
							fieldLabel:'症状',
							anchor:'98%',
							allowBlank:false
						}
					]
				},{
					items:[
						{
							xtype:'combo',
							fieldLabel:'食量',
							hiddenName:'shiliang',
							store:new Ext.data.SimpleStore({
								data:array.shiliang,
								fields:['text']
							}),
							displayField:'text',
							valueField:'text',
							mode:'local',
							triggerAction:'all'
						},{
							xtype:'combo',
							fieldLabel:'体重',
							hiddenName:'tizhong',
							store:new Ext.data.SimpleStore({
								data:array.tizhong,
								fields:['text']
							}),
							displayField:'text',
							valueField:'text',
							mode:'local',
							triggerAction:'all'
						},{
							xtype:'combo',
							fieldLabel:'尿量',
							hiddenName:'niaoliang',
							store:new Ext.data.SimpleStore({
								data:array.niaoliang,
								fields:['text']
							}),
							displayField:'text',
							valueField:'text',
							mode:'local',
							triggerAction:'all'
						}
					]
				},{
					items:[
						{
							xtype:'combo',
							fieldLabel:'睡眠',
							hiddenName:'shuimian',
							store:new Ext.data.SimpleStore({
								data:array.shuimian,
								fields:['text']
							}),
							displayField:'text',
							valueField:'text',
							mode:'local',
							triggerAction:'all'
						},{
							xtype:'combo',
							fieldLabel:'精神状态',
							hiddenName:'jingshen',
							store:new Ext.data.SimpleStore({
								data:array.jingshen,
								fields:['text']
							}),
							displayField:'text',
							valueField:'text',
							mode:'local',
							triggerAction:'all'
						},{
							xtype:'combo',
							fieldLabel:'大便',
							hiddenName:'dabian',
							store:new Ext.data.SimpleStore({
								data:array.dabian,
								fields:['text']
							}),
							displayField:'text',
							valueField:'text',
							mode:'local',
							triggerAction:'all'
						}
					]
				},{
					columnWidth:1,
					items:[
						{
							xtype:'combo',
							fieldLabel:'病情演变',
							hiddenName:'yanbian',
							store:new Ext.data.SimpleStore({
								data:array.yanbian,
								fields:['text']
							}),
							displayField:'text',
							valueField:'text',
							mode:'local',
							triggerAction:'all',
							anchor:'98%'
						},{
							xtype:'textarea',
							fieldLabel:'治疗情况',
							name:'zhiliao',
							height:50,
							anchor:'98%'
						},{
							xtype:'textarea',
							fieldLabel:'好转方面',
							name:'haozhuan',
							height:50,
							anchor:'98%'
						},{
							xtype:'textarea',
							fieldLabel:'就诊目标',
							name:'jiuzhen',
							height:50,
							anchor:'98%'
						},{
							xtype:'hidden',
							name:'id'
						}
					]
				}
			]
		});
		Ext.apply(this,{
			title:'健康记录',
			closable:false,
			width:450,
			autoHeight:true,
			buttonAlign:'center',
			frame:true,
			layout:'form',
			layout:'fit',
			items:form,
			buttons:[]
		});
		var btn1=new Ext.Button({
			text:'保存',
			handler:function(){
				var win=this.ownerCt;
				if(win.items.get(0).getForm().isValid()){
					Ext.Ajax.request({
						url:App.App_Info.BasePath+'/module/biomedical/member.do?method=saveMyHealthRecords',
						params:{
							data:Ext.encode(win.items.get(0).getForm().getValues())
						},
						success:function(response){
							var res=Ext.decode(response.responseText);
							if(res.success){
								alert('保存成功。');
								win.hide();
								Ext.getCmp('grid').getStore().reload();
							}else{
								alert('保存失败。');
							}
						}
					});
				}else{
					alert('表单未通过验证，填写完整后提交。');
				}
			}
		});
		this.buttons.push(btn1);
		var btn2=new Ext.Button({
			text:'取消',
			handler:function(){
				this.ownerCt.hide();
			}
		});
		this.buttons.push(btn2);
		Member.HR.RegistForm.superclass.initComponent.call(this,arguments);
	}
});